apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ride-buddy-frontend
spec:
  type: NodePort
  selector:
    app: ride-buddy-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30007

